#!/bin/bash
SITE_PKG=$(python3 -c 'import sysconfig; print(sysconfig.get_paths()["purelib"])')

cp -v stablebear/*.py "$SITE_PKG/stablebear/"
cp -v cmake-build-debug/_sb_cpu.*.so "$SITE_PKG/stablebear/"
cp -v cmake-build-debug/_gpu_detect.*.so "$SITE_PKG/stablebear/" 2>/dev/null || true
cp -v cmake-build-debug/_sb_cuda*.so "$SITE_PKG/stablebear/" 2>/dev/null || true

