name: CompileCheck

on:
  workflow_dispatch:

concurrency:
  group: compile-${{ github.ref }}
  cancel-in-progress: true

jobs:
  compile:
    name: Compile on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-22.04-arm, macos-26, windows-2022]

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive

      - uses: astral-sh/setup-uv@v7

      - name: Compile Python 3.13 wheel
        uses: pypa/cibuildwheel@v3.3.1
        env:
          CIBW_BUILD: "cp313-*"
          CIBW_BUILD_FRONTEND: "build[uv]"
          CIBW_ENVIRONMENT_LINUX: BUILD_WITH_CUDA=0
          CIBW_ENVIRONMENT_MACOS: >-
            BUILD_WITH_CUDA=0
            MACOSX_DEPLOYMENT_TARGET=11.0
          CIBW_ENVIRONMENT_WINDOWS: BUILD_WITH_CUDA=0
          CIBW_TEST_SKIP: "*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
