name: Run Python tests

on: [workflow_dispatch] #push TODO: Revert this

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.10"] #["3.9", "3.10", "3.11", "3.12", "3.13"]
      
    env:
      BUILD_WITH_CUDA: 0
      PIP_RETRIES: 5
      PIP_DEFAULT_TIMEOUT: 60

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'recursive'
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build module
        run: bash .github/scripts/ci-retry.sh pip install .

      - name: Install dependencies
        run: bash .github/scripts/ci-retry.sh pip install pytest pytest-cov scipy
      
      - name: Run tests
        working-directory: ./test
        run: pytest --cov=stablebear -v python
      
